# Generated by Django 4.2 on 2023-04-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_description_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(default='', max_length=10),
        ),
    ]
